web:
  image: ec2-54-175-26-39.compute-1.amazonaws.com:8080/iporaitech_web:0.1.0
  ports:
    - "3002:80"
    - "2224:22"
  links:
    - db
  environment:
    RAILS_ENV: production
    PASSENGER_APP_ENV: production
  volumes:
    - /mnt/volumes/iporaitech/logs/app:/home/app/webapp/log

db:
  image: postgres:9.4.4
  ports:
    - "55434:5432"
  volumes:
    - /mnt/volumes/iporaitech/logs/var:/var/logs
    - /mnt/volumes/iporaitech/db:/var/lib/postgresql/data